// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Delicious Team"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/cleanup-images": {
            "post": {
                "description": "对比数据库引用和磁盘文件，列出未被引用的孤立图片。仅本地存储模式可用",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理"
                ],
                "summary": "扫描孤立图片",
                "responses": {
                    "200": {
                        "description": "result: total_files, orphan_files, freed_bytes",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Blob 存储不支持此功能",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/admin/cleanup-images/execute": {
            "post": {
                "description": "删除所有未被引用的孤立图片。仅本地存储模式可用",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "系统管理"
                ],
                "summary": "执行图片清理",
                "responses": {
                    "200": {
                        "description": "result: total_files, orphan_files(已删除), freed_bytes",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Blob 存储不支持此功能",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/categories": {
            "get": {
                "description": "获取全部分类（字典表）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "分类管理"
                ],
                "summary": "分类列表",
                "responses": {
                    "200": {
                        "description": "items",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "新增一个分类名称",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "分类管理"
                ],
                "summary": "创建分类",
                "parameters": [
                    {
                        "description": "{\\",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "category",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "名称不能为空",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/categories/{id}": {
            "put": {
                "description": "修改分类名称",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "分类管理"
                ],
                "summary": "修改分类",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "分类 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "{\\",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "category",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "无效 ID 或名称为空",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "删除一个分类",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "分类管理"
                ],
                "summary": "删除分类",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "分类 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "分类不存在",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/dashboard/recipes/{id}/timeline": {
            "get": {
                "description": "获取菜谱完整时间线：基本信息 + 所有版本节点 + 当前版本标记",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据面板"
                ],
                "summary": "菜谱时间线",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "菜谱 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "recipe, timeline[]",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "菜谱不存在",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/dashboard/stats": {
            "get": {
                "description": "返回当前用户的统计概览：总菜谱数、平均评分、总版本数、评分分布",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "数据面板"
                ],
                "summary": "数据总览",
                "responses": {
                    "200": {
                        "description": "total_recipes, average_rating, total_versions, rating_distribution[], latest_recipe_at",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/encyclopedia/category/{category}": {
            "get": {
                "description": "获取某个分类下的所有百科菜谱",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "百科菜谱"
                ],
                "summary": "按分类浏览百科",
                "parameters": [
                    {
                        "type": "string",
                        "description": "分类名称，如 川菜、西餐",
                        "name": "category",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "返回语言 zh/en",
                        "name": "lang",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "items[], page_info",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/encyclopedia/search": {
            "get": {
                "description": "搜索百科菜谱库。优先聚合免费中文源 HowToCook、Proj.Kitchen，并辅以 Spoonacular、TheMealDB、Forkify、DummyJSON；结果会缓存到数据库供详情查看。支持中英翻译",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "百科菜谱"
                ],
                "summary": "搜索百科菜谱",
                "parameters": [
                    {
                        "type": "string",
                        "description": "搜索关键词（中英文均可）",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "分类筛选",
                        "name": "category",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "en",
                        "description": "返回语言 zh/en",
                        "name": "lang",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "items[], page_info",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "服务端错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/encyclopedia/{id}": {
            "get": {
                "description": "获取百科菜谱的完整信息，包括配料和制作步骤。浏览量自动 +1。支持翻译",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "百科菜谱"
                ],
                "summary": "百科菜谱详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "百科菜谱 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "返回语言 zh/en",
                        "name": "lang",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "recipe",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "菜谱不存在",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/encyclopedia/{id}/tags": {
            "get": {
                "description": "查看某个百科菜谱的所有标签",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "标签管理"
                ],
                "summary": "获取菜谱关联的标签",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "百科菜谱 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "items",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "为百科菜谱关联一个标签",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "标签管理"
                ],
                "summary": "给菜谱添加标签",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "百科菜谱 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "{\\",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "integer",
                                "format": "int64"
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "{}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "tag_id 无效",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/encyclopedia/{id}/tags/{tag_id}": {
            "delete": {
                "description": "取消百科菜谱与标签的关联",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "标签管理"
                ],
                "summary": "移除菜谱的标签",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "百科菜谱 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "标签 ID",
                        "name": "tag_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "关联不存在",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/recipes": {
            "get": {
                "description": "分页获取当前用户的菜谱列表，支持关键词搜索、评分筛选、排序",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜谱管理"
                ],
                "summary": "菜谱列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "菜名搜索关键词",
                        "name": "keyword",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "最低评分 (1-5)",
                        "name": "min_rating",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "最高评分 (1-5)",
                        "name": "max_rating",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "created_at",
                            "updated_at",
                            "user_rating"
                        ],
                        "type": "string",
                        "default": "updated_at",
                        "description": "排序字段",
                        "name": "order_by",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "default": true,
                        "description": "是否降序",
                        "name": "desc",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "创建时间起点 (RFC3339)",
                        "name": "created_after",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "创建时间终点 (RFC3339)",
                        "name": "created_before",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "items[], page_info",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "新建菜谱并自动创建第一个版本（version 1）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜谱管理"
                ],
                "summary": "创建菜谱",
                "parameters": [
                    {
                        "description": "菜谱信息",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "recipe",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "服务端错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/recipes/export": {
            "get": {
                "description": "导出当前用户所有菜谱（含当前版本完整数据）为 JSON",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "导入导出"
                ],
                "summary": "导出菜谱",
                "responses": {
                    "200": {
                        "description": "recipes",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/recipes/import": {
            "post": {
                "description": "从 JSON 导入菜谱。按 name 去重：已存在则追加新版本，不存在则新建",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "导入导出"
                ],
                "summary": "导入菜谱",
                "parameters": [
                    {
                        "description": "{\\",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "result",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/recipes/trash": {
            "get": {
                "description": "查看已删除的菜谱",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "回收站"
                ],
                "summary": "回收站列表",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页数量",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "items[], page_info",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/recipes/{id}": {
            "get": {
                "description": "根据 ID 获取菜谱及当前版本完整信息",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜谱管理"
                ],
                "summary": "获取菜谱详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "菜谱 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "recipe",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "菜谱不存在",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "编辑菜谱会新增一个不可变版本（版本号+1），不会修改旧版本",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜谱管理"
                ],
                "summary": "编辑菜谱",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "菜谱 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新内容",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "recipe",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "菜谱不存在",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "软删除菜谱，移入回收站。30 天内可通过 /restore 恢复",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "菜谱管理"
                ],
                "summary": "删除菜谱（软删除）",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "菜谱 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "菜谱不存在",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/recipes/{id}/diff": {
            "get": {
                "description": "O(n+m) 算法对比两个版本的配料和步骤差异，返回中文摘要",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "版本管理"
                ],
                "summary": "对比两个版本",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "菜谱 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "基准版本 ID",
                        "name": "base_version_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "对比版本 ID",
                        "name": "target_version_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "base_version, target_version, diff",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/recipes/{id}/diff/encyclopedia": {
            "get": {
                "description": "将菜谱当前版本与关联的百科菜谱进行对比",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "版本管理"
                ],
                "summary": "与百科基准对比",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "菜谱 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "指定百科菜谱 ID（可选，默认用菜谱已关联的）",
                        "name": "encyclopedia_recipe_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "encyclopedia_recipe_id, encyclopedia_name, encyclopedia_ingredients, encyclopedia_process_steps, my_version, diff",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/recipes/{id}/permanent": {
            "delete": {
                "description": "彻底删除菜谱，不可恢复",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "回收站"
                ],
                "summary": "物理删除",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "菜谱 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: 已彻底删除",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "菜谱不在回收站中",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/recipes/{id}/restore": {
            "post": {
                "description": "从回收站恢复已删除的菜谱",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "回收站"
                ],
                "summary": "恢复菜谱",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "菜谱 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "message: 已恢复",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "菜谱不在回收站中",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/recipes/{id}/versions": {
            "get": {
                "description": "获取某个菜谱的所有历史版本，按版本号降序",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "版本管理"
                ],
                "summary": "版本历史列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "菜谱 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "versions",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "菜谱不存在",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/recipes/{id}/versions/{version_id}": {
            "get": {
                "description": "查看某个历史版本的完整配料和步骤",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "版本管理"
                ],
                "summary": "获取某个版本详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "菜谱 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "版本 ID",
                        "name": "version_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "version",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "版本不存在",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/tags": {
            "get": {
                "description": "获取全部标签（字典表）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "标签管理"
                ],
                "summary": "标签列表",
                "responses": {
                    "200": {
                        "description": "items",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "description": "新增一个标签名称",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "标签管理"
                ],
                "summary": "创建标签",
                "parameters": [
                    {
                        "description": "{\\",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "tag",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "名称不能为空",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/tags/{id}": {
            "delete": {
                "description": "删除一个标签（同时清除关联关系）",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "标签管理"
                ],
                "summary": "删除标签",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "标签 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "标签不存在",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/upload": {
            "post": {
                "description": "上传一张图片（JPG/PNG/WebP/GIF），最大 10MB。Vercel 环境自动使用 Blob 存储",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "图片上传"
                ],
                "summary": "上传单张图片",
                "parameters": [
                    {
                        "type": "file",
                        "description": "图片文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "url, filename, size",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "文件格式不支持或超过大小限制",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/upload/batch": {
            "post": {
                "description": "一次上传多张图片，返回全部上传结果",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "图片上传"
                ],
                "summary": "批量上传图片",
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "file"
                        },
                        "collectionFormat": "csv",
                        "description": "图片文件数组",
                        "name": "files",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "files",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "文件格式不支持",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "人间烟火 (Delicious) API",
	Description:      "家庭菜谱管理系统 — 支持菜谱版本控制、百科搜索、翻译、导入导出\n所有接口前缀 /api/v1，单用户模式（无需认证）",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
